import os

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from game.models import Question

extra_questions = [
    # MATH - Dif 1
    {
        "c": "MATH",
        "d": 1,
        "t": "Quanto fa 10 - 4?",
        "o1": "4",
        "o2": "5",
        "o3": "6",
        "o4": "7",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 1,
        "t": "Quanto fa 5 x 5?",
        "o1": "10",
        "o2": "20",
        "o3": "25",
        "o4": "55",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 1,
        "t": "Quanto fa 12 + 8?",
        "o1": "18",
        "o2": "19",
        "o3": "20",
        "o4": "21",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 1,
        "t": "Quanto fa 30 diviso 5?",
        "o1": "5",
        "o2": "6",
        "o3": "7",
        "o4": "8",
        "co": 2,
    },
    {
        "c": "MATH",
        "d": 1,
        "t": "Qual è il doppio di 20?",
        "o1": "30",
        "o2": "40",
        "o3": "50",
        "o4": "60",
        "co": 2,
    },
    # MATH - Dif 2
    {
        "c": "MATH",
        "d": 2,
        "t": "Qual è la radice quadrata di 64?",
        "o1": "6",
        "o2": "7",
        "o3": "8",
        "o4": "9",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 2,
        "t": "Quanto fa 2 elevato alla 3a (2^3)?",
        "o1": "6",
        "o2": "8",
        "o3": "12",
        "o4": "16",
        "co": 2,
    },
    {
        "c": "MATH",
        "d": 2,
        "t": "Quant'è il 15% di 100?",
        "o1": "10",
        "o2": "15",
        "o3": "20",
        "o4": "25",
        "co": 2,
    },
    {
        "c": "MATH",
        "d": 2,
        "t": "Risolvi: 18 / 3 + 2",
        "o1": "4",
        "o2": "6",
        "o3": "8",
        "o4": "10",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 2,
        "t": "Qual è il minimo comune multiplo tra 3 e 4?",
        "o1": "7",
        "o2": "12",
        "o3": "24",
        "o4": "1",
        "co": 2,
    },
    # MATH - Dif 3
    {
        "c": "MATH",
        "d": 3,
        "t": "Risolvi: 5x = 25",
        "o1": "x=2",
        "o2": "x=3",
        "o3": "x=4",
        "o4": "x=5",
        "co": 4,
    },
    {
        "c": "MATH",
        "d": 3,
        "t": "Qual è l'area di un quadrato con lato 12?",
        "o1": "24",
        "o2": "48",
        "o3": "144",
        "o4": "124",
        "co": 3,
    },
    {
        "c": "MATH",
        "d": 3,
        "t": "Logaritmo in base 10 di 1000",
        "o1": "2",
        "o2": "3",
        "o3": "10",
        "o4": "100",
        "co": 2,
    },
    {
        "c": "MATH",
        "d": 3,
        "t": "Radice cubica di 27",
        "o1": "2",
        "o2": "3",
        "o3": "4",
        "o4": "9",
        "co": 2,
    },
    {
        "c": "MATH",
        "d": 3,
        "t": "Risolvi: (5 - 2)^3",
        "o1": "9",
        "o2": "18",
        "o3": "27",
        "o4": "8",
        "co": 3,
    },
    # GEO - Dif 1
    {
        "c": "GEO",
        "d": 1,
        "t": "Qual è la capitale dell'Inghilterra?",
        "o1": "Parigi",
        "o2": "Londra",
        "o3": "Dublino",
        "o4": "Roma",
        "co": 2,
    },
    {
        "c": "GEO",
        "d": 1,
        "t": "In quale continente si trova il Giappone?",
        "o1": "Africa",
        "o2": "Europa",
        "o3": "Asia",
        "o4": "Oceania",
        "co": 3,
    },
    {
        "c": "GEO",
        "d": 1,
        "t": "Dove si trova la Torre Eiffel?",
        "o1": "Roma",
        "o2": "Madrid",
        "o3": "Londra",
        "o4": "Parigi",
        "co": 4,
    },
    {
        "c": "GEO",
        "d": 1,
        "t": "Quali sono i colori della bandiera italiana?",
        "o1": "Rosso, Bianco, Verde",
        "o2": "Verde, Bianco, Rosso",
        "o3": "Bianco, Rosso, Verde",
        "o4": "Verde, Rosso, Bianco",
        "co": 2,
    },
    {
        "c": "GEO",
        "d": 1,
        "t": "Come viene chiamata spesso la Terra per via dei suoi oceani?",
        "o1": "Pianeta Verde",
        "o2": "Pianeta Blu",
        "o3": "Pianeta Rosso",
        "o4": "Pianeta Acqua",
        "co": 2,
    },
    # GEO - Dif 2
    {
        "c": "GEO",
        "d": 2,
        "t": "Quale fiume bagna Roma?",
        "o1": "Po",
        "o2": "Tevere",
        "o3": "Arno",
        "o4": "Adige",
        "co": 2,
    },
    {
        "c": "GEO",
        "d": 2,
        "t": "Qual è la capitale della Germania?",
        "o1": "Monaco",
        "o2": "Francoforte",
        "o3": "Berlino",
        "o4": "Amburgo",
        "co": 3,
    },
    {
        "c": "GEO",
        "d": 2,
        "t": "Quale catena montuosa separa naturalmente l'Europa dall'Asia?",
        "o1": "Alpi",
        "o2": "Himalaya",
        "o3": "Monti Urali",
        "o4": "Pirenei",
        "co": 3,
    },
    {
        "c": "GEO",
        "d": 2,
        "t": "Quale oceano separa l'America dall'Europa?",
        "o1": "Pacifico",
        "o2": "Indiano",
        "o3": "Atlantico",
        "o4": "Artico",
        "co": 3,
    },
    {
        "c": "GEO",
        "d": 2,
        "t": "Qual è la capitale del Giappone?",
        "o1": "Pechino",
        "o2": "Seul",
        "o3": "Bangkok",
        "o4": "Tokyo",
        "co": 4,
    },
    # GEO - Dif 3
    {
        "c": "GEO",
        "d": 3,
        "t": "Qual è la capitale della Nuova Zelanda?",
        "o1": "Auckland",
        "o2": "Wellington",
        "o3": "Christchurch",
        "o4": "Sydney",
        "co": 2,
    },
    {
        "c": "GEO",
        "d": 3,
        "t": "Qual è il fiume più lungo dell'Asia?",
        "o1": "Gange",
        "o2": "Fiume Giallo",
        "o3": "Fiume Azzurro (Yangtze)",
        "o4": "Mekong",
        "co": 3,
    },
    {
        "c": "GEO",
        "d": 3,
        "t": "Qual è il deserto non polare più grande del mondo?",
        "o1": "Gobi",
        "o2": "Kalahari",
        "o3": "Atacama",
        "o4": "Sahara",
        "co": 4,
    },
    {
        "c": "GEO",
        "d": 3,
        "t": "Quale stretto divide l'Asia dall'America del Nord?",
        "o1": "Gibilterra",
        "o2": "Bering",
        "o3": "Magellano",
        "o4": "Bosforo",
        "co": 2,
    },
    {
        "c": "GEO",
        "d": 3,
        "t": "In quale stato si trova il sito archeologico di Machu Picchu?",
        "o1": "Messico",
        "o2": "Cile",
        "o3": "Perù",
        "o4": "Bolivia",
        "co": 3,
    },
    # ENG - Dif 1
    {
        "c": "ENG",
        "d": 1,
        "t": "Come si dice 'Giallo' in inglese?",
        "o1": "Red",
        "o2": "Blue",
        "o3": "Yellow",
        "o4": "Green",
        "co": 3,
    },
    {
        "c": "ENG",
        "d": 1,
        "t": "Come si traduce 'Acqua' in inglese?",
        "o1": "Fire",
        "o2": "Earth",
        "o3": "Air",
        "o4": "Water",
        "co": 4,
    },
    {
        "c": "ENG",
        "d": 1,
        "t": "Come si dice 'Mela' in inglese?",
        "o1": "Orange",
        "o2": "Apple",
        "o3": "Banana",
        "o4": "Pear",
        "co": 2,
    },
    {
        "c": "ENG",
        "d": 1,
        "t": "Uno, Due, Tre in inglese?",
        "o1": "One, Two, Three",
        "o2": "Un, Do, Tre",
        "o3": "First, Second, Third",
        "o4": "A, B, C",
        "co": 1,
    },
    {
        "c": "ENG",
        "d": 1,
        "t": "Qual è il plurale di 'Car'?",
        "o1": "Cares",
        "o2": "Car",
        "o3": "Cars",
        "o4": "Cari",
        "co": 3,
    },
    # ENG - Dif 2
    {
        "c": "ENG",
        "d": 2,
        "t": "Qual è il Past Simple di 'Make'?",
        "o1": "Maked",
        "o2": "Made",
        "o3": "Make",
        "o4": "Making",
        "co": 2,
    },
    {
        "c": "ENG",
        "d": 2,
        "t": "Qual è il sinonimo di 'Fast'?",
        "o1": "Slow",
        "o2": "Quick",
        "o3": "Heavy",
        "o4": "Hard",
        "co": 2,
    },
    {
        "c": "ENG",
        "d": 2,
        "t": "Come si traduce 'Sempre' in inglese?",
        "o1": "Never",
        "o2": "Sometimes",
        "o3": "Often",
        "o4": "Always",
        "co": 4,
    },
    {
        "c": "ENG",
        "d": 2,
        "t": "Qual è il comparativo di 'Good'?",
        "o1": "Gooder",
        "o2": "More good",
        "o3": "Better",
        "o4": "Best",
        "co": 3,
    },
    {
        "c": "ENG",
        "d": 2,
        "t": "Cosa significa il verbo 'To buy'?",
        "o1": "Vendere",
        "o2": "Comprare",
        "o3": "Portare",
        "o4": "Vedere",
        "co": 2,
    },
    # ENG - Dif 3
    {
        "c": "ENG",
        "d": 3,
        "t": "Qual è il Present Perfect di 'Drink'?",
        "o1": "Has drank",
        "o2": "Has drunk",
        "o3": "Has drinked",
        "o4": "Drank",
        "co": 2,
    },
    {
        "c": "ENG",
        "d": 3,
        "t": "Cosa significa il phrasal verb 'Take off' (riferito a un aereo)?",
        "o1": "Atterrare",
        "o2": "Ritardare",
        "o3": "Decollare",
        "o4": "Esplodere",
        "co": 3,
    },
    {
        "c": "ENG",
        "d": 3,
        "t": "Qual è il plurale irregolare di 'Mouse'?",
        "o1": "Mouses",
        "o2": "Mice",
        "o3": "Meese",
        "o4": "Mices",
        "co": 2,
    },
    {
        "c": "ENG",
        "d": 3,
        "t": "Qual è il contrario di 'Narrow'?",
        "o1": "Wide",
        "o2": "Short",
        "o3": "Deep",
        "o4": "High",
        "co": 1,
    },
    {
        "c": "ENG",
        "d": 3,
        "t": "Cosa significa l'idioma 'It costs an arm and a leg'?",
        "o1": "E' pericoloso",
        "o2": "E' faticoso",
        "o3": "Costa moltissimo",
        "o4": "E' gratis",
        "co": 3,
    },
    # CHEM - Dif 1
    {
        "c": "CHEM",
        "d": 1,
        "t": "Qual è il simbolo chimico dell'Ossigeno?",
        "o1": "Os",
        "o2": "O",
        "o3": "Ox",
        "o4": "O2",
        "co": 2,
    },
    {
        "c": "CHEM",
        "d": 1,
        "t": "A quale temperatura bolle l'acqua (a livello del mare)?",
        "o1": "50 °C",
        "o2": "90 °C",
        "o3": "100 °C",
        "o4": "120 °C",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 1,
        "t": "Come chiamiamo comunemente il Saccarosio?",
        "o1": "Sale",
        "o2": "Pepe",
        "o3": "Farina",
        "o4": "Zucchero",
        "co": 4,
    },
    {
        "c": "CHEM",
        "d": 1,
        "t": "Cos'è l'H2O?",
        "o1": "Aria",
        "o2": "Fuoco",
        "o3": "Acqua",
        "o4": "Terra",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 1,
        "t": "Qual è il simbolo chimico del Carbonio?",
        "o1": "Ca",
        "o2": "Co",
        "o3": "Cr",
        "o4": "C",
        "co": 4,
    },
    # CHEM - Dif 2
    {
        "c": "CHEM",
        "d": 2,
        "t": "Qual è il pH dell'acqua pura?",
        "o1": "1",
        "o2": "7",
        "o3": "14",
        "o4": "0",
        "co": 2,
    },
    {
        "c": "CHEM",
        "d": 2,
        "t": "Qual è il simbolo chimico del Rame?",
        "o1": "Rm",
        "o2": "Ra",
        "o3": "Cu",
        "o4": "Co",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 2,
        "t": "Quanti protoni ha un atomo di Ossigeno?",
        "o1": "6",
        "o2": "8",
        "o3": "10",
        "o4": "12",
        "co": 2,
    },
    {
        "c": "CHEM",
        "d": 2,
        "t": "L'unione di un acido e una base forma acqua e...",
        "o1": "Zucchero",
        "o2": "Alcool",
        "o3": "Sale",
        "o4": "Gas",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 2,
        "t": "Qual è la formula del metano?",
        "o1": "CO2",
        "o2": "CH4",
        "o3": "H2O",
        "o4": "NH3",
        "co": 2,
    },
    # CHEM - Dif 3
    {
        "c": "CHEM",
        "d": 3,
        "t": "Qual è l'elemento più elettronegativo della tavola periodica?",
        "o1": "Fluoro",
        "o2": "Ossigeno",
        "o3": "Cloro",
        "o4": "Azoto",
        "co": 1,
    },
    {
        "c": "CHEM",
        "d": 3,
        "t": "Quale ibridazione ha il carbonio nella molecola di metano?",
        "o1": "sp",
        "o2": "sp2",
        "o3": "sp3",
        "o4": "sp4",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 3,
        "t": "Chi ha inventato la dinamite?",
        "o1": "Einstein",
        "o2": "Nobel",
        "o3": "Curie",
        "o4": "Oppenheimer",
        "co": 2,
    },
    {
        "c": "CHEM",
        "d": 3,
        "t": "Quale isotopo del carbonio si usa per la radiodatazione?",
        "o1": "Carbonio-12",
        "o2": "Carbonio-13",
        "o3": "Carbonio-14",
        "o4": "Carbonio-15",
        "co": 3,
    },
    {
        "c": "CHEM",
        "d": 3,
        "t": "Qual è l'unico metallo liquido a temperatura ambiente?",
        "o1": "Gallio",
        "o2": "Mercurio",
        "o3": "Piombo",
        "o4": "Oro",
        "co": 2,
    },
    # SCI - Dif 1
    {
        "c": "SCI",
        "d": 1,
        "t": "Quale pianeta è conosciuto come il 'Pianeta Rosso'?",
        "o1": "Venere",
        "o2": "Giove",
        "o3": "Marte",
        "o4": "Saturno",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 1,
        "t": "Quale animale terrestre ha il collo lunghissimo?",
        "o1": "Zebra",
        "o2": "Leone",
        "o3": "Giraffa",
        "o4": "Elefante",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 1,
        "t": "A quale classe di animali appartiene l'uomo?",
        "o1": "Rettili",
        "o2": "Anfibi",
        "o3": "Uccelli",
        "o4": "Mammiferi",
        "co": 4,
    },
    {
        "c": "SCI",
        "d": 1,
        "t": "Qual è la stella più vicina alla Terra?",
        "o1": "Sirio",
        "o2": "Sole",
        "o3": "Stella Polare",
        "o4": "Alpha Centauri",
        "co": 2,
    },
    {
        "c": "SCI",
        "d": 1,
        "t": "Quante zampe ha un ragno?",
        "o1": "4",
        "o2": "6",
        "o3": "8",
        "o4": "10",
        "co": 3,
    },
    # SCI - Dif 2
    {
        "c": "SCI",
        "d": 2,
        "t": "Chi è stato il primo uomo a camminare sulla Luna?",
        "o1": "Yuri Gagarin",
        "o2": "Neil Armstrong",
        "o3": "Buzz Aldrin",
        "o4": "Michael Collins",
        "co": 2,
    },
    {
        "c": "SCI",
        "d": 2,
        "t": "Qual è l'osso più lungo del corpo umano?",
        "o1": "Omero",
        "o2": "Tibia",
        "o3": "Femore",
        "o4": "Radio",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 2,
        "t": "Gli insetti hanno un numero di zampe pari a...",
        "o1": "4",
        "o2": "6",
        "o3": "8",
        "o4": "10",
        "co": 2,
    },
    {
        "c": "SCI",
        "d": 2,
        "t": "Quale gas nell'atmosfera ci protegge dai raggi UV?",
        "o1": "Ossigeno",
        "o2": "Azoto",
        "o3": "Anidride Carbonica",
        "o4": "Ozono",
        "co": 4,
    },
    {
        "c": "SCI",
        "d": 2,
        "t": "Chi ha formulato la teoria dell'Evoluzione per selezione naturale?",
        "o1": "Charles Darwin",
        "o2": "Gregor Mendel",
        "o3": "Louis Pasteur",
        "o4": "Isaac Newton",
        "co": 1,
    },
    # SCI - Dif 3
    {
        "c": "SCI",
        "d": 3,
        "t": "A quanto si stima l'età dell'Universo?",
        "o1": "13.8 milioni di anni",
        "o2": "13.8 miliardi di anni",
        "o3": "4.5 miliardi di anni",
        "o4": "Infinito",
        "co": 2,
    },
    {
        "c": "SCI",
        "d": 3,
        "t": "Qual è la velocità della luce nel vuoto (approssimata)?",
        "o1": "300.000 km/h",
        "o2": "300.000 m/s",
        "o3": "300.000 km/s",
        "o4": "3.000 km/s",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 3,
        "t": "Qual è l'animale vivente più veloce (in picchiata)?",
        "o1": "Ghepardo",
        "o2": "Aquila reale",
        "o3": "Falco pellegrino",
        "o4": "Rondine",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 3,
        "t": "Quale proteina trasporta l'ossigeno nei globuli rossi?",
        "o1": "Cheratina",
        "o2": "Collagene",
        "o3": "Emoglobina",
        "o4": "Insulina",
        "co": 3,
    },
    {
        "c": "SCI",
        "d": 3,
        "t": "Cosa ha scoperto Alexander Fleming?",
        "o1": "Raggi X",
        "o2": "Penicillina",
        "o3": "Struttura del DNA",
        "o4": "Vaccino antirabbico",
        "co": 2,
    },
    # ITA - Dif 1
    {
        "c": "ITA",
        "d": 1,
        "t": "Qual è il plurale di 'Amico'?",
        "o1": "Amici",
        "o2": "Amice",
        "o3": "Amichi",
        "o4": "Amicos",
        "co": 1,
    },
    {
        "c": "ITA",
        "d": 1,
        "t": "Qual è un sinonimo di 'Bello'?",
        "o1": "Brutto",
        "o2": "Cattivo",
        "o3": "Stupendo",
        "o4": "Sporco",
        "co": 3,
    },
    {
        "c": "ITA",
        "d": 1,
        "t": "Qual è la prima lettera dell'alfabeto italiano?",
        "o1": "B",
        "o2": "Z",
        "o3": "A",
        "o4": "E",
        "co": 3,
    },
    {
        "c": "ITA",
        "d": 1,
        "t": "Completa il verbo mangiare: Io ...",
        "o1": "Mangi",
        "o2": "Mangio",
        "o3": "Mangiamo",
        "o4": "Mangerò",
        "co": 2,
    },
    {
        "c": "ITA",
        "d": 1,
        "t": "Qual è il contrario di 'Alto'?",
        "o1": "Grande",
        "o2": "Basso",
        "o3": "Grasso",
        "o4": "Lungo",
        "co": 2,
    },
    # ITA - Dif 2
    {
        "c": "ITA",
        "d": 2,
        "t": "Quale categoria grammaticale è la parola 'Casa'?",
        "o1": "Verbo",
        "o2": "Aggettivo",
        "o3": "Nome (Sostantivo)",
        "o4": "Pronome",
        "co": 3,
    },
    {
        "c": "ITA",
        "d": 2,
        "t": "Quante sillabe ha la parola 'Tavolo'?",
        "o1": "2",
        "o2": "3",
        "o3": "4",
        "o4": "5",
        "co": 2,
    },
    {
        "c": "ITA",
        "d": 2,
        "t": "A quale coniugazione appartiene il verbo 'Andare'?",
        "o1": "Prima",
        "o2": "Seconda",
        "o3": "Terza",
        "o4": "Nessuna",
        "co": 1,
    },
    {
        "c": "ITA",
        "d": 2,
        "t": "Io, tu, egli sono...",
        "o1": "Avverbi",
        "o2": "Pronomi personali",
        "o3": "Aggettivi qualificativi",
        "o4": "Preposizioni",
        "co": 2,
    },
    {
        "c": "ITA",
        "d": 2,
        "t": "Chi è l'autore de 'Le avventure di Pinocchio'?",
        "o1": "Gianni Rodari",
        "o2": "Italo Calvino",
        "o3": "Carlo Collodi",
        "o4": "Alessandro Manzoni",
        "co": 3,
    },
    # ITA - Dif 3
    {
        "c": "ITA",
        "d": 3,
        "t": "Cos'è una sinestesia?",
        "o1": "Accostamento di due concetti opposti",
        "o2": "Sostituzione di una parola con un'altra",
        "o3": "Associazione di termini appartenenti a sfere sensoriali diverse",
        "o4": "Ripetizione della stessa vocale",
        "co": 3,
    },
    {
        "c": "ITA",
        "d": 3,
        "t": "Chi ha scritto 'L'Orlando Furioso'?",
        "o1": "Torquato Tasso",
        "o2": "Ludovico Ariosto",
        "o3": "Dante Alighieri",
        "o4": "Giovanni Boccaccio",
        "co": 2,
    },
    {
        "c": "ITA",
        "d": 3,
        "t": "Da quanti canti è composta in totale la Divina Commedia?",
        "o1": "99",
        "o2": "100",
        "o3": "33",
        "o4": "101",
        "co": 2,
    },
    {
        "c": "ITA",
        "d": 3,
        "t": "La frase 'Se io sarei' è...",
        "o1": "Corretta in italiano antico",
        "o2": "Sempre corretta",
        "o3": "Un errore grammaticale",
        "o4": "Un congiuntivo",
        "co": 3,
    },
    {
        "c": "ITA",
        "d": 3,
        "t": "Qual è il participio passato del verbo 'Cuocere'?",
        "o1": "Cociuto",
        "o2": "Cotto",
        "o3": "Cuociuto",
        "o4": "Cocetto",
        "co": 2,
    },
    # HIST - Dif 1
    {
        "c": "HIST",
        "d": 1,
        "t": "In che anno l'uomo è sbarcato sulla Luna?",
        "o1": "1959",
        "o2": "1969",
        "o3": "1979",
        "o4": "1989",
        "co": 2,
    },
    {
        "c": "HIST",
        "d": 1,
        "t": "Quale animale veniva adorato nell'antico Egitto?",
        "o1": "Gatto",
        "o2": "Cane",
        "o3": "Cavallo",
        "o4": "Topo",
        "co": 1,
    },
    {
        "c": "HIST",
        "d": 1,
        "t": "Dove vivevano i faraoni?",
        "o1": "A Roma",
        "o2": "In Grecia",
        "o3": "In Egitto",
        "o4": "In Cina",
        "co": 3,
    },
    {
        "c": "HIST",
        "d": 1,
        "t": "Secondo la leggenda, chi ha fondato Roma?",
        "o1": "Cesare",
        "o2": "Augusto",
        "o3": "Romolo",
        "o4": "Enea",
        "co": 3,
    },
    {
        "c": "HIST",
        "d": 1,
        "t": "Quali sono i colori della bandiera degli Stati Uniti?",
        "o1": "Rosso, Bianco, Blu",
        "o2": "Rosso, Giallo, Verde",
        "o3": "Bianco, Rosso, Verde",
        "o4": "Nero, Rosso, Giallo",
        "co": 1,
    },
    # HIST - Dif 2
    {
        "c": "HIST",
        "d": 2,
        "t": "In che anno è scoppiata la Prima Guerra Mondiale?",
        "o1": "1914",
        "o2": "1918",
        "o3": "1939",
        "o4": "1945",
        "co": 1,
    },
    {
        "c": "HIST",
        "d": 2,
        "t": "Chi è stato assassinato alle Idi di Marzo?",
        "o1": "Marco Antonio",
        "o2": "Ottaviano",
        "o3": "Giulio Cesare",
        "o4": "Nerone",
        "co": 3,
    },
    {
        "c": "HIST",
        "d": 2,
        "t": "In che anno è stata scoperta l'America?",
        "o1": "1492",
        "o2": "1500",
        "o3": "1512",
        "o4": "1402",
        "co": 1,
    },
    {
        "c": "HIST",
        "d": 2,
        "t": "Chi inventò la stampa a caratteri mobili in Europa?",
        "o1": "Galileo",
        "o2": "Leonardo da Vinci",
        "o3": "Gutenberg",
        "o4": "Newton",
        "co": 3,
    },
    {
        "c": "HIST",
        "d": 2,
        "t": "Chi dipinse il quadro della 'Gioconda'?",
        "o1": "Michelangelo",
        "o2": "Leonardo da Vinci",
        "o3": "Raffaello",
        "o4": "Caravaggio",
        "co": 2,
    },
    # HIST - Dif 3
    {
        "c": "HIST",
        "d": 3,
        "t": "In che anno si svolse la Battaglia di Lepanto?",
        "o1": "1492",
        "o2": "1571",
        "o3": "1610",
        "o4": "1648",
        "co": 2,
    },
    {
        "c": "HIST",
        "d": 3,
        "t": "Chi era soprannominato il 'Re Sole'?",
        "o1": "Luigi XIV di Francia",
        "o2": "Enrico VIII d'Inghilterra",
        "o3": "Carlo V",
        "o4": "Filippo II di Spagna",
        "co": 1,
    },
    {
        "c": "HIST",
        "d": 3,
        "t": "In che anno ci fu la Rivoluzione Russa (d'Ottobre)?",
        "o1": "1905",
        "o2": "1914",
        "o3": "1917",
        "o4": "1922",
        "co": 3,
    },
    {
        "c": "HIST",
        "d": 3,
        "t": "Chi scrisse il 'Manifesto del Partito Comunista'?",
        "o1": "Lenin e Stalin",
        "o2": "Marx e Engels",
        "o3": "Trotsky",
        "o4": "Mao Zedong",
        "co": 2,
    },
    {
        "c": "HIST",
        "d": 3,
        "t": "Chi fu il successore di Augusto come imperatore di Roma?",
        "o1": "Tiberio",
        "o2": "Caligola",
        "o3": "Claudio",
        "o4": "Nerone",
        "co": 1,
    },
]

for q in extra_questions:
    Question.objects.update_or_create(
        text=q["t"],
        defaults={
            "category": q["c"],
            "difficulty": q["d"],
            "option_1": q["o1"],
            "option_2": q["o2"],
            "option_3": q["o3"],
            "option_4": q["o4"],
            "correct_option": q["co"],
        },
    )

print(
    f"Inserite o aggiornate altre {len(extra_questions)} domande. Il database cresce!"
)
