[dependency-groups]
dev = [
  "bandit>=1.9.4",
  "djlint>=1.39.5",
  "pre-commit>=4.6.0",
  "ruff>=0.15.20"
]

[project]
dependencies = [
  "django>=6.0.6",
  "django-environ>=0.14.0",
  "django-htmx>=1.27.0",
  "granian[pname]>=2.2.0",
  "playwright>=1.62.0",
  "whitenoise[brotli]>=6.12.0"
]
description = "Add your description here"
name = "monstercraft"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[tool.bandit]
skips = ["B101", "B311"]

[tool.djlint]
ignore = "T002,H006"
profile = "django"

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
ignore = ["E501", "E741", "F405"]
select = ["E", "F", "B", "I"]

[tool.ruff.lint.per-file-ignores]
"extra_seed_*.py" = ["E402"]
"seed_*.py" = ["E402"]
