import os

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from game.models import HangmanWord

words = [
    # 5-8 ANNI
    ("CANE", "Migliore amico dell'uomo", 1, "5-8"),
    ("GATTO", "Animale che fa miao", 1, "5-8"),
    ("MELA", "Frutto rosso o verde", 1, "5-8"),
    ("SOLE", "Splende di giorno", 1, "5-8"),
    ("LUNA", "Splende di notte", 1, "5-8"),
    ("GIOCO", "Attività divertente", 1, "5-8"),
    ("BIMBO", "Un bambino piccolo", 1, "5-8"),
    ("TOPO", "Mangia il formaggio", 1, "5-8"),
    ("CASA", "Dove si abita", 1, "5-8"),
    ("FIORE", "Profuma in primavera", 2, "5-8"),
    ("CIELO", "Azzurro e grandissimo", 2, "5-8"),
    ("CUORE", "Simbolo dell'amore", 2, "5-8"),
    ("STELLA", "Brilla nel cielo notturno", 2, "5-8"),
    ("NUVOLA", "Bianca nel cielo", 2, "5-8"),
    ("ACQUA", "Si beve per dissetarsi", 2, "5-8"),
    ("PRATO", "È verde e ci si può giocare", 2, "5-8"),
    ("MARE", "Acqua salata per nuotare", 2, "5-8"),
    ("SORRISO", "Si fa quando si è felici", 3, "5-8"),
    ("PALLONCINO", "Si gonfia alle feste", 3, "5-8"),
    ("ARCOBALENO", "I sette colori dopo la pioggia", 3, "5-8"),
    ("ZAINETTO", "Si usa per andare a scuola", 3, "5-8"),
    ("GELATO", "Dolce freddo ed estivo", 3, "5-8"),
    ("FARFALLA", "Insetto colorato che vola", 3, "5-8"),
    ("TARTARUGA", "Animale con il guscio lento", 3, "5-8"),
    ("NEVE", "Cade in inverno ed è bianca", 1, "5-8"),
    ("FOGLIA", "Cade dagli alberi in autunno", 1, "5-8"),
    ("SASSO", "Pietra piccola", 1, "5-8"),
    ("TAVOLO", "Ci si mangia sopra", 1, "5-8"),
    ("SEDIA", "Serve per sedersi", 1, "5-8"),
    ("VENTO", "Aria che si muove veloce", 2, "5-8"),
    ("FUOCO", "Brucia e scalda", 2, "5-8"),
    ("TERRA", "Il pianeta su cui viviamo", 2, "5-8"),
    ("NUOTO", "Si fa in piscina o in mare", 2, "5-8"),
    ("MAGIA", "La fa il mago", 2, "5-8"),
    ("PIUMA", "Leggerissima, degli uccelli", 2, "5-8"),
    ("SABBIA", "In spiaggia per fare castelli", 2, "5-8"),
    ("AEROPLANO", "Vola in alto nel cielo", 3, "5-8"),
    ("ELICOTTERO", "Vola con una grande elica", 3, "5-8"),
    ("SOTTOMARINO", "Va sotto il mare", 3, "5-8"),
    ("BICICLETTA", "Ha due ruote e si pedala", 3, "5-8"),
    ("FORMICA", "Insetto piccolo e lavoratore", 3, "5-8"),
    ("SCOIATTOLO", "Animale che mangia le noci", 3, "5-8"),
    ("GIRAFFA", "Ha un collo lunghissimo", 3, "5-8"),
    ("ELEFANTE", "Animale enorme con la proboscide", 3, "5-8"),

    # 9-12 ANNI
    ("ALBERO", "Ha foglie e tronco", 1, "9-12"),
    ("SCUOLA", "Dove si va per imparare", 1, "9-12"),
    ("MUSICA", "Si ascolta e si balla", 1, "9-12"),
    ("PIANETA", "La Terra lo è", 1, "9-12"),
    ("LIBRO", "Si legge per viaggiare con la mente", 1, "9-12"),
    ("SPORT", "Fa bene al corpo e alla mente", 1, "9-12"),
    ("AMICO", "Una persona di cui ti fidi", 1, "9-12"),
    ("ISOLA", "Terra circondata dal mare", 1, "9-12"),
    ("CORAGGIO", "Forza d'animo", 2, "9-12"),
    ("SQUADRA", "Un gruppo unito che gioca insieme", 2, "9-12"),
    ("FANTASIA", "Immaginare mondi magici", 2, "9-12"),
    ("SCOPERTA", "Trovare qualcosa di nuovo", 2, "9-12"),
    ("VITTORIA", "Quando si vince una gara", 2, "9-12"),
    ("MISTERO", "Qualcosa ancora da svelare", 2, "9-12"),
    ("UNIVERSO", "L'insieme di tutto lo spazio", 2, "9-12"),
    ("CHITARRA", "Strumento a corde", 2, "9-12"),
    ("AVVENTURA", "Un viaggio emozionante", 3, "9-12"),
    ("SPETTACOLO", "Cose bellissime da guardare", 3, "9-12"),
    ("INVENZIONE", "Creare qualcosa che non esisteva", 3, "9-12"),
    ("CONOSCENZA", "Sapere tante cose nuove", 3, "9-12"),
    ("OROLOGIO", "Misura il trascorrere del tempo", 3, "9-12"),
    ("ASTRONAUTA", "Viaggia nello spazio", 3, "9-12"),
    ("ESPLORATORE", "Chi viaggia in terre sconosciute", 3, "9-12"),
    ("LABIRINTO", "Un percorso da cui è difficile uscire", 3, "9-12"),
    ("VIAGGIO", "Spostarsi per scoprire il mondo", 1, "9-12"),
    ("MONTAGNA", "Rilievo molto alto", 1, "9-12"),
    ("DESERTO", "Luogo pieno di sabbia e caldo", 1, "9-12"),
    ("OCEANO", "Una grandissima distesa d'acqua", 1, "9-12"),
    ("FIUME", "Corso d'acqua dolce", 1, "9-12"),
    ("GHIACCIAIO", "Grande massa di ghiaccio", 2, "9-12"),
    ("VULCANO", "Montagna che erutta lava", 2, "9-12"),
    ("CASCATA", "Acqua che cade dall'alto", 2, "9-12"),
    ("FORESTA", "Grande bosco selvaggio", 2, "9-12"),
    ("GIUNGLA", "Foresta tropicale intricata", 2, "9-12"),
    ("CASTELLO", "Dove vivevano re e regine", 2, "9-12"),
    ("CAVALIERE", "Guerriero in armatura", 2, "9-12"),
    ("MICROSCOPIO", "Per vedere cose minuscole", 3, "9-12"),
    ("TELESCOPIO", "Per guardare le stelle", 3, "9-12"),
    ("DINOSAURO", "Rettile gigante estinto", 3, "9-12"),
    ("REGINA", "Moglie del re", 3, "9-12"),
    ("FARAONE", "Antico re d'Egitto", 3, "9-12"),
    ("TESORO", "Ricchezze nascoste", 3, "9-12"),
    ("ASTRONOMIA", "Scienza che studia le stelle", 3, "9-12"),
    ("MATEMATICA", "Scienza dei numeri", 3, "9-12"),

    # 13-17 ANNI
    ("INTERNET", "La rete globale", 1, "13-17"),
    ("COMPUTER", "Macchina per elaborare dati", 1, "13-17"),
    ("SISTEMA", "Insieme di elementi connessi", 1, "13-17"),
    ("TECNOLOGIA", "Scienza applicata", 1, "13-17"),
    ("ENERGIA", "Capacità di compiere lavoro", 1, "13-17"),
    ("GRAVITA", "Forza che ci tiene a terra", 1, "13-17"),
    ("CELLULA", "L'unità base della vita", 1, "13-17"),
    ("GALASSIA", "Insieme di stelle e pianeti", 2, "13-17"),
    ("ELETTRONE", "Particella con carica negativa", 2, "13-17"),
    ("HARDWARE", "Componenti fisiche di un PC", 2, "13-17"),
    ("SOFTWARE", "I programmi di un computer", 2, "13-17"),
    ("ATOMO", "L'unità base della materia", 2, "13-17"),
    ("MOLECOLA", "Insieme di atomi legati", 2, "13-17"),
    ("EVOLUZIONE", "Sviluppo delle specie nel tempo", 2, "13-17"),
    ("FOTOSINTESI", "Processo che usa la luce solare", 2, "13-17"),
    ("ALGORITMO", "Sequenza logica di istruzioni", 3, "13-17"),
    ("METABOLISMO", "Insieme delle reazioni chimiche nel corpo", 3, "13-17"),
    ("CRITTOGRAFIA", "Tecnica per nascondere messaggi", 3, "13-17"),
    ("ECOSISTEMA", "Ambiente e organismi che lo abitano", 3, "13-17"),
    ("DNA", "Codice genetico della vita", 3, "13-17"),
    ("PROSPETTIVA", "Punto di vista o tecnica di disegno", 3, "13-17"),
    ("CIBERNETICA", "Scienza dei sistemi di controllo", 3, "13-17"),
    ("INTUIZIONE", "Comprensione immediata di qualcosa", 3, "13-17"),
    ("INFORMAZIONE", "Dato elaborato e utile", 1, "13-17"),
    ("COMUNICAZIONE", "Scambio di messaggi", 1, "13-17"),
    ("ECOLOGIA", "Studio delle relazioni degli esseri viventi", 1, "13-17"),
    ("RICICLO", "Riutilizzo dei materiali", 1, "13-17"),
    ("CLIMA", "Condizioni atmosferiche medie", 1, "13-17"),
    ("SIMBIOSI", "Convivenza vantaggiosa tra specie", 2, "13-17"),
    ("EREDITARIETA", "Trasmissione di caratteri genetici", 2, "13-17"),
    ("ANTICORPO", "Proteina per la difesa immunitaria", 2, "13-17"),
    ("VIRUS", "Microrganismo infettivo", 2, "13-17"),
    ("BATTERIO", "Microrganismo unicellulare", 2, "13-17"),
    ("ORBITA", "Traiettoria di un corpo celeste", 2, "13-17"),
    ("SATELLITE", "Corpo che orbita intorno a un pianeta", 2, "13-17"),
    ("NEUROLOGIA", "Branca della medicina per il sistema nervoso", 3, "13-17"),
    ("PSICOLOGIA", "Studio della mente", 3, "13-17"),
    ("FILOSOFIA", "Amore per la sapienza", 3, "13-17"),
    ("LETTERATURA", "L'arte della parola scritta", 3, "13-17"),
    ("RINASCIMENTO", "Periodo artistico e culturale storico", 3, "13-17"),
    ("ILLUMINISMO", "Movimento culturale del Settecento", 3, "13-17"),
    ("ROBOTICA", "Scienza che progetta robot", 3, "13-17"),
    ("BIOTECNOLOGIA", "Tecnologia basata sulla biologia", 3, "13-17"),

    # ADULT
    ("ECONOMIA", "Scienza che studia produzione e consumo", 1, "ADULT"),
    ("POLITICA", "Arte del governare", 1, "ADULT"),
    ("SOCIETA", "Insieme di individui", 1, "ADULT"),
    ("ELEZIONI", "Si va a votare", 1, "ADULT"),
    ("CONTRATTO", "Accordo legale", 1, "ADULT"),
    ("CULTURA", "Insieme di tradizioni e saperi", 1, "ADULT"),
    ("DIRITTO", "Insieme delle leggi", 1, "ADULT"),
    ("INFLAZIONE", "Aumento generale dei prezzi", 2, "ADULT"),
    ("DEMOCRAZIA", "Forma di governo", 2, "ADULT"),
    ("SINDACATO", "Associazione di lavoratori", 2, "ADULT"),
    ("MERCATO", "Luogo di scambio economico", 2, "ADULT"),
    ("TASSATIVO", "Che non ammette deroghe", 2, "ADULT"),
    ("INVESTIMENTO", "Impiego di capitale a scopo di lucro", 2, "ADULT"),
    ("COSTITUZIONE", "Legge fondamentale dello Stato", 2, "ADULT"),
    ("BUROCRAZIA", "Apparato amministrativo", 2, "ADULT"),
    ("REFERENDUM", "Votazione popolare diretta", 3, "ADULT"),
    ("MACROECONOMIA", "Studio del sistema economico globale", 3, "ADULT"),
    ("PSICANALISI", "Teoria fondata da Freud", 3, "ADULT"),
    ("GLOBALIZZAZIONE", "Mercato unico mondiale", 3, "ADULT"),
    ("NEUROSCIENZE", "Studio del sistema nervoso", 3, "ADULT"),
    ("SOCIOLOGIA", "Scienza che studia la società", 3, "ADULT"),
    ("ESISTENZIALISMO", "Corrente filosofica", 3, "ADULT"),
    ("INFRASTRUTTURA", "Reti e impianti di base", 3, "ADULT"),
    ("ANTROPOLOGIA", "Scienza che studia l'uomo", 3, "ADULT"),
    ("FINANZA", "Gestione del denaro", 1, "ADULT"),
    ("ASSICURAZIONE", "Contratto contro i rischi", 1, "ADULT"),
    ("PENSIONE", "Rendita dopo la vita lavorativa", 1, "ADULT"),
    ("TASSE", "Tributi da pagare allo Stato", 1, "ADULT"),
    ("BILANCIO", "Resoconto finanziario", 1, "ADULT"),
    ("DEFLAZIONE", "Diminuzione generale dei prezzi", 2, "ADULT"),
    ("OLIGOPOLIO", "Mercato in mano a pochi venditori", 2, "ADULT"),
    ("MONOPOLIO", "Mercato in mano a un solo venditore", 2, "ADULT"),
    ("AZIONISTA", "Proprietario di quote societarie", 2, "ADULT"),
    ("DIVIDENDO", "Quota di utile distribuita", 2, "ADULT"),
    ("SPREAD", "Differenza di rendimento tra titoli", 2, "ADULT"),
    ("GEOFISICA", "Scienza della fisica terrestre", 3, "ADULT"),
    ("EPISTEMOLOGIA", "Filosofia della scienza", 3, "ADULT"),
    ("FENOMENOLOGIA", "Metodo filosofico basato sui fenomeni", 3, "ADULT"),
    ("GEOSTRATEGIA", "Studio dello spazio geopolitico", 3, "ADULT"),
    ("MULTILATERALISMO", "Relazioni tra più nazioni", 3, "ADULT"),
    ("SOSTENIBILITA", "Sviluppo che non danneggia il futuro", 3, "ADULT"),
    ("METAVERSO", "Spazio virtuale condiviso", 3, "ADULT"),
    ("CRIPTOVALUTA", "Moneta digitale decentralizzata", 3, "ADULT"),
]

print("Cancellazione vecchie parole in corso...")
HangmanWord.objects.all().delete()

for w, h, d, age in words:
    HangmanWord.objects.create(word=w, hint=h, difficulty=d, age_group=age)

print(f"Caricate {len(words)} nuove parole per l'impiccato suddivise per fasce d'età!")
