# Generated by Django 6.0.6 on 2026-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Facile"), (2, "Medio"), (3, "Difficile")],
                default=1,
                verbose_name="Difficoltà",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("MATH", "Matematica"),
                    ("GEO", "Geografia"),
                    ("ENG", "Inglese"),
                    ("CHEM", "Chimica"),
                    ("SCI", "Scienze"),
                    ("ITA", "Italiano"),
                ],
                default="MATH",
                max_length=10,
            ),
        ),
    ]
