# Generated by Django 6.0.6 on 2026-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_question_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initials", models.CharField(max_length=3, verbose_name="Iniziali")),
                ("score", models.IntegerField(verbose_name="Punteggio")),
                ("level", models.IntegerField(verbose_name="Livello Raggiunto")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Punteggio",
                "verbose_name_plural": "Punteggi",
                "ordering": ["-score", "-level"],
            },
        ),
    ]
