# Generated by Django 6.0.6 on 2026-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_hangmanword"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("5-8", "5-8 anni"),
                    ("9-12", "9-12 anni"),
                    ("13-17", "13-17 anni"),
                    ("ADULT", "Adulto"),
                ],
                default="9-12",
                max_length=10,
                verbose_name="Fascia d'età",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("MATH", "Matematica"),
                    ("GEO", "Geografia"),
                    ("ENG", "Inglese"),
                    ("CHEM", "Chimica"),
                    ("SCI", "Scienze"),
                    ("ITA", "Italiano"),
                    ("HIST", "Storia"),
                    ("TECH", "Tecnologia"),
                    ("ART", "Arte"),
                    ("PHIL", "Filosofia"),
                ],
                default="MATH",
                max_length=10,
            ),
        ),
    ]
