# Generated by Django 6.0.6 on 2026-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_hangmanword_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MATH', 'Matematica'), ('GEO', 'Geografia'), ('ENG', 'Inglese'), ('CHEM', 'Chimica'), ('SCI', 'Scienze'), ('ITA', 'Italiano'), ('HIST', 'Storia'), ('TECH', 'Tecnologia'), ('ART', 'Arte'), ('CURR', 'Attualità')], default='MATH', max_length=10),
        ),
    ]
