# Generated by Django 6.0.6 on 2026-06-29 14:24

from django.db import migrations


def add_words(apps, schema_editor):
    HangmanWord = apps.get_model('game', 'HangmanWord')
    words = [
        # 5-8
        ("GATTO", "Animale che fa miao", 1, "5-8"),
        ("CANE", "Il miglior amico dell'uomo", 1, "5-8"),
        ("SOLE", "Brilla di giorno", 1, "5-8"),
        ("LUNA", "Nel cielo di notte", 1, "5-8"),
        ("MARE", "Acqua salata grandissima", 2, "5-8"),
        ("NEVE", "Fredda e bianca", 2, "5-8"),
        ("TORTA", "Si mangia al compleanno", 2, "5-8"),
        ("GIOCO", "Ci si diverte molto", 3, "5-8"),
        ("COLORI", "Ci sono nell'astuccio", 3, "5-8"),
        ("FAVOLA", "Storia prima di dormire", 3, "5-8"),
        
        # 9-12
        ("LIBRO", "Ha tante pagine scritte", 1, "9-12"),
        ("SPORT", "Fa bene alla salute", 1, "9-12"),
        ("AMICO", "Con lui giochi e parli", 1, "9-12"),
        ("NATURA", "Alberi, prati, animali", 1, "9-12"),
        ("MISTERO", "Un segreto da svelare", 2, "9-12"),
        ("ENERGIA", "Per correre serve questa", 2, "9-12"),
        ("SCIENZA", "Studia come funziona il mondo", 2, "9-12"),
        ("RISPETTO", "Si deve a tutte le persone", 3, "9-12"),
        ("TALENTO", "Essere molto bravi in qualcosa", 3, "9-12"),
        ("PROGETTO", "Un'idea da realizzare", 3, "9-12"),
        
        # 13-17
        ("STUDIO", "Impegno sui libri", 1, "13-17"),
        ("SOCIETA", "Insieme di persone", 1, "13-17"),
        ("FUTURO", "Quello che deve ancora succedere", 1, "13-17"),
        ("CULTURA", "Patrimonio di conoscenze", 2, "13-17"),
        ("BIOLOGIA", "Studia gli esseri viventi", 2, "13-17"),
        ("CHIMICA", "Scienza delle reazioni", 2, "13-17"),
        ("TEOREMA", "Va dimostrato in matematica", 3, "13-17"),
        ("GENETICA", "Studia il DNA", 3, "13-17"),
        ("FILOSOFIA", "L'amore per la saggezza", 3, "13-17"),
        
        # ADULT
        ("LAVORO", "Occupa gran parte della giornata", 1, "ADULT"),
        ("TASSE", "Si pagano allo stato", 1, "ADULT"),
        ("MUTUO", "Prestito per la casa", 1, "ADULT"),
        ("FAMIGLIA", "Le persone più vicine a te", 1, "ADULT"),
        ("PENSIONE", "Riposo dopo anni di lavoro", 2, "ADULT"),
        ("CARRIERA", "Il percorso lavorativo", 2, "ADULT"),
        ("BOLLETTA", "Va pagata ogni mese", 2, "ADULT"),
        ("BORSA", "Dove si scambiano azioni", 3, "ADULT"),
        ("DIRITTO", "Insieme di norme giuridiche", 3, "ADULT"),
        ("ANTROPOLOGIA", "Studio del genere umano", 3, "ADULT"),
    ]
    for word, hint, diff, age in words:
        HangmanWord.objects.create(word=word, hint=hint, difficulty=diff, age_group=age)

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_score_age_group'),
    ]

    operations = [
        migrations.RunPython(add_words),
    ]
